---
title: "講演"
---

## 招待講演


---
title: "発表 / Presentations"
---

## 国際会議における発表

口頭 2 件、ポスター 2 件

1. Kengo Shinoda, Ryo Sawada, Yudai Suwa, Takeru Suzuki, Ryosuke Hirai, Kazunari Iwasaki, Kengo Tomida, “The Correlation between Supernova Fallback and Progenitor’s Hydrogen Envelope” (Poster), *The Progenitors of Supernovae and their Explosions* (2024, Dali, China).

2. Kengo Shinoda, Ryo Sawada, Yudai Suwa, Takeru Suzuki, Ryosuke Hirai, Kazunari Iwasaki, Kengo Tomida, “Impact of Progenitor Hydrogen Envelope on Supernova Fallback” (Oral), *Breaking New Ground in Supernova Physics 2025 (BNGSP25)* (2025, Fukuoka University, Japan).

3. Kengo Shinoda, Ryo Sawada, Yudai Suwa, Takeru Suzuki, Ryosuke Hirai, Kazunari Iwasaki, Kengo Tomida, “The Correlation Between Supernova Fallback and Progenitor’s Hydrogen Envelope” (Oral), *SN2025gw: First IGWN Symposium on Core Collapse Supernova Gravitational Wave Theory and Detection* (2025, University of Warsaw, Poland).

4. Kengo Shinoda, Ryo Tazaki, Takato Tokuno, Yudai Suwa, “Dust Formation in Failed Supernovae” (Poster), *Yukawa International Seminar 2026a (YKIS2026a)* (2026, Kyoto University, Japan).

## 国内会議における発表

1. 篠田兼伍, 澤田涼, 諏訪雄大, 岩崎一成, 富田賢吾, “超新星爆発 fallback に向けた自己重力流体シミュレーション開発” (ポスター), *第35回理論懇シンポジウム* (2022, 福島県, コラッセふくしま).

2. 篠田兼伍, 澤田涼, 諏訪雄大, 岩崎一成, 富田賢吾, “超新星フォールバックと親星水素外層の相関性” (口頭), *日本天文学会 2023年秋年会* (2023, 名古屋大学).

3. 篠田兼伍, 澤田涼, 諏訪雄大, 岩崎一成, 富田賢吾, “超新星フォールバックと親星水素外層の相関性” (ポスター), *第36回理論懇シンポジウム* (2023, 弘前大学).

4. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 岩崎一成, 富田賢吾, “超新星フォールバック計算のための境界条件開発” (口頭), *日本天文学会 2024年春年会* (2024, 東京大学).

5. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 平井遼介, 岩崎一成, 富田賢吾, “後期中性子星熱進化のための超新星フォールバック計算” (ポスター), *学術変革「地下稀事象」領域研究会* (2024, 大阪大学).

6. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 平井遼介, 岩崎一成, 富田賢吾, “超新星爆発フォールバック計算のための新手法開発” (口頭), *日本天文学会 2024年秋年会* (2024, 関西学院大学).

7. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 平井遼介, 岩崎一成, 富田賢吾, “超新星フォールバックと水素外層の相関性” (口頭), *超新星ミーティング@福井* (2024, 福井県あわら市清風荘).

8. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 平井遼介, 岩崎一成, 富田賢吾, “超新星フォールバックの数値流体シミュレーション” (口頭), *高エネルギー宇宙物理学研究会 2024* (2024, 東北大学).

9. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 平井遼介, 岩崎一成, 富田賢吾, “超新星フォールバックの数値流体シミュレーション” (ポスター), *第37回理論懇シンポジウム* (2024, 国立天文台).

10. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 平井遼介, 岩崎一成, 富田賢吾, “超新星フォールバックの数値流体シミュレーション” (口頭), *第11回超新星ニュートリノ研究会* (2025, 東京大学).

11. 篠田兼伍, 澤田涼, 諏訪雄大, 鈴木建, 平井遼介, 岩崎一成, 富田賢吾, “超新星フォールバックの流体シミュレーション” (口頭), *日本天文学会 2025年春年会* (2025, 茨城県水戸市, 水戸市民会館).

12. 篠田兼伍, 田崎亮, 徳野鷹人, 諏訪雄大, “超新星爆発によるダスト形成の網羅的なパラメータ調査” (口頭), *日本惑星科学会 2025年秋季講演会* (2025, 東京大学駒場 I キャンパス).

13. 篠田兼伍, 田崎亮, 徳野鷹人, 諏訪雄大, “失敗型超新星におけるダスト形成” (口頭), *初代星・初代銀河研究会 2025 初代星から生命へ* (2025, AOSSA, 福井).

14. 篠田兼伍, 田崎亮, 徳野鷹人, 諏訪雄大, “失敗型超新星におけるダスト形成進化計算” (ポスター), *高エネルギー宇宙物理学研究会 2025* (2025, 大阪大学).

15. 篠田兼伍, 田崎亮, 徳野鷹人, 諏訪雄大, “失敗型超新星におけるダスト形成” (口頭), *第38回理論懇シンポジウム* (2025, 筑波大学).

16. 篠田兼伍, 田崎亮, 徳野鷹人, 諏訪雄大, “Dust formation in failed supernova” (口頭), *マルチメッセンジャー天文学冬の学校 2026* (2026, 菅平高原ホテル柄澤).

17. 篠田兼伍, 田崎亮, 徳野鷹人, 諏訪雄大, “トランジェント天体におけるダスト形成” (口頭), *惑星形成討論会 2026* (2026, 東北大学).

18. 篠田兼伍, 田崎亮, 徳野鷹人, 諏訪雄大, “失敗型超新星におけるダスト形成” (口頭), *日本天文学会 2026年春年会* (2026, 京都産業大学).